# SPDX-FileCopyrightText: 2025 Jens Pitkänen <jens.pitkanen@helsinki.fi>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
members = [
    "platform-abstraction-layer",
    "engine",
    "import-asset",
    "platform-sdl2",
    "example",
]
resolver = "2"

[profile.release]
debug = "full"
