# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
    "platform",
    "engine",
    "import-asset",
    "platform-sdl2",
    "example",
]
resolver = "2"

[profile.release]
debug = "full"
