[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
bytemuck = { version = "1.20.0", default-features = false }
enum-map = { version = "2.7.3", default-features = false }
glam = { version = "0.29.2", default-features = false }
pal = { version = "0.1.0", path = "../pal" }

[features]
default = ["libm"]

std = ["glam/std"]
libm = ["glam/libm"]
