# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v3
    - run: cargo fmt --check
    - run: env RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
    - run: cargo clippy --all-targets --all-features -- --no-deps -D warnings
