name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-stable:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y libsdl2-dev
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/checkout@v3
    - run: cargo test --all-features
  test-nightly-miri:
    runs-on: ubuntu-latest
    steps:
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    - uses: actions/checkout@v3
    - run: cargo miri test --all-features
